#!/bin/bash

curl http://vimdoc.sourceforge.net/htmldoc/arabic.html > app/src/main/assets/vim/arabic.html
curl http://vimdoc.sourceforge.net/htmldoc/autocmd.html > app/src/main/assets/vim/autocmd.html
curl http://vimdoc.sourceforge.net/htmldoc/change.html > app/src/main/assets/vim/change.html
curl http://vimdoc.sourceforge.net/htmldoc/channel.html > app/src/main/assets/vim/channel.html
curl http://vimdoc.sourceforge.net/htmldoc/cmdline.html > app/src/main/assets/vim/cmdline.html
curl http://vimdoc.sourceforge.net/htmldoc/debug.html > app/src/main/assets/vim/debug.html
curl http://vimdoc.sourceforge.net/htmldoc/debugger.html > app/src/main/assets/vim/debugger.html
curl http://vimdoc.sourceforge.net/htmldoc/develop.html > app/src/main/assets/vim/develop.html
curl http://vimdoc.sourceforge.net/htmldoc/diff.html > app/src/main/assets/vim/diff.html
curl http://vimdoc.sourceforge.net/htmldoc/digraph.html > app/src/main/assets/vim/digraph.html
curl http://vimdoc.sourceforge.net/htmldoc/editing.html > app/src/main/assets/vim/editing.html
curl http://vimdoc.sourceforge.net/htmldoc/eval.html > app/src/main/assets/vim/eval.html
curl http://vimdoc.sourceforge.net/htmldoc/farsi.html > app/src/main/assets/vim/farsi.html
curl http://vimdoc.sourceforge.net/htmldoc/filetype.html > app/src/main/assets/vim/filetype.html
curl http://vimdoc.sourceforge.net/htmldoc/fold.html > app/src/main/assets/vim/fold.html
curl http://vimdoc.sourceforge.net/htmldoc/ft_ada.html > app/src/main/assets/vim/ft_ada.html
curl http://vimdoc.sourceforge.net/htmldoc/ft_rust.html > app/src/main/assets/vim/ft_rust.html
curl http://vimdoc.sourceforge.net/htmldoc/ft_sql.html > app/src/main/assets/vim/ft_sql.html
curl http://vimdoc.sourceforge.net/htmldoc/gui.html > app/src/main/assets/vim/gui.html
curl http://vimdoc.sourceforge.net/htmldoc/gui_w32.html > app/src/main/assets/vim/gui_w32.html
curl http://vimdoc.sourceforge.net/htmldoc/gui_x11.html > app/src/main/assets/vim/gui_x11.html
curl http://vimdoc.sourceforge.net/htmldoc/hangulin.html > app/src/main/assets/vim/hangulin.html
curl http://vimdoc.sourceforge.net/htmldoc/hebrew.html > app/src/main/assets/vim/hebrew.html
curl http://vimdoc.sourceforge.net/htmldoc/help.html > app/src/main/assets/vim/help.html
curl http://vimdoc.sourceforge.net/htmldoc/helphelp.html > app/src/main/assets/vim/helphelp.html
curl http://vimdoc.sourceforge.net/htmldoc/howto.html > app/src/main/assets/vim/howto.html
curl http://vimdoc.sourceforge.net/htmldoc/if_cscop.html > app/src/main/assets/vim/if_cscop.html
curl http://vimdoc.sourceforge.net/htmldoc/if_lua.html > app/src/main/assets/vim/if_lua.html
curl http://vimdoc.sourceforge.net/htmldoc/if_mzsch.html > app/src/main/assets/vim/if_mzsch.html
curl http://vimdoc.sourceforge.net/htmldoc/if_ole.html > app/src/main/assets/vim/if_ole.html
curl http://vimdoc.sourceforge.net/htmldoc/if_perl.html > app/src/main/assets/vim/if_perl.html
curl http://vimdoc.sourceforge.net/htmldoc/if_pyth.html > app/src/main/assets/vim/if_pyth.html
curl http://vimdoc.sourceforge.net/htmldoc/if_ruby.html > app/src/main/assets/vim/if_ruby.html
curl http://vimdoc.sourceforge.net/htmldoc/if_sniff.html > app/src/main/assets/vim/if_sniff.html
curl http://vimdoc.sourceforge.net/htmldoc/if_tcl.html > app/src/main/assets/vim/if_tcl.html
curl http://vimdoc.sourceforge.net/htmldoc/indent.html > app/src/main/assets/vim/indent.html
curl http://vimdoc.sourceforge.net/htmldoc/index.html > app/src/main/assets/vim/index.html
curl http://vimdoc.sourceforge.net/htmldoc/insert.html > app/src/main/assets/vim/insert.html
curl http://vimdoc.sourceforge.net/htmldoc/intro.html > app/src/main/assets/vim/intro.html
curl http://vimdoc.sourceforge.net/htmldoc/map.html > app/src/main/assets/vim/map.html
curl http://vimdoc.sourceforge.net/htmldoc/mbyte.html > app/src/main/assets/vim/mbyte.html
curl http://vimdoc.sourceforge.net/htmldoc/message.html > app/src/main/assets/vim/message.html
curl http://vimdoc.sourceforge.net/htmldoc/mlang.html > app/src/main/assets/vim/mlang.html
curl http://vimdoc.sourceforge.net/htmldoc/motion.html > app/src/main/assets/vim/motion.html
curl http://vimdoc.sourceforge.net/htmldoc/netbeans.html > app/src/main/assets/vim/netbeans.html
curl http://vimdoc.sourceforge.net/htmldoc/options.html > app/src/main/assets/vim/options.html
curl http://vimdoc.sourceforge.net/htmldoc/os_390.html > app/src/main/assets/vim/os_390.html
curl http://vimdoc.sourceforge.net/htmldoc/os_amiga.html > app/src/main/assets/vim/os_amiga.html
curl http://vimdoc.sourceforge.net/htmldoc/os_beos.html > app/src/main/assets/vim/os_beos.html
curl http://vimdoc.sourceforge.net/htmldoc/os_dos.html > app/src/main/assets/vim/os_dos.html
curl http://vimdoc.sourceforge.net/htmldoc/os_mac.html > app/src/main/assets/vim/os_mac.html
curl http://vimdoc.sourceforge.net/htmldoc/os_mint.html > app/src/main/assets/vim/os_mint.html
curl http://vimdoc.sourceforge.net/htmldoc/os_msdos.html > app/src/main/assets/vim/os_msdos.html
curl http://vimdoc.sourceforge.net/htmldoc/os_os2.html > app/src/main/assets/vim/os_os2.html
curl http://vimdoc.sourceforge.net/htmldoc/os_qnx.html > app/src/main/assets/vim/os_qnx.html
curl http://vimdoc.sourceforge.net/htmldoc/os_risc.html > app/src/main/assets/vim/os_risc.html
curl http://vimdoc.sourceforge.net/htmldoc/os_unix.html > app/src/main/assets/vim/os_unix.html
curl http://vimdoc.sourceforge.net/htmldoc/os_vms.html > app/src/main/assets/vim/os_vms.html
curl http://vimdoc.sourceforge.net/htmldoc/os_win32.html > app/src/main/assets/vim/os_win32.html
curl http://vimdoc.sourceforge.net/htmldoc/pattern.html > app/src/main/assets/vim/pattern.html
curl http://vimdoc.sourceforge.net/htmldoc/pi_getscript.html > app/src/main/assets/vim/pi_getscript.html
curl http://vimdoc.sourceforge.net/htmldoc/pi_gzip.html > app/src/main/assets/vim/pi_gzip.html
curl http://vimdoc.sourceforge.net/htmldoc/pi_logipat.html > app/src/main/assets/vim/pi_logipat.html
curl http://vimdoc.sourceforge.net/htmldoc/pi_netrw.html > app/src/main/assets/vim/pi_netrw.html
curl http://vimdoc.sourceforge.net/htmldoc/pi_paren.html > app/src/main/assets/vim/pi_paren.html
curl http://vimdoc.sourceforge.net/htmldoc/pi_spec.html > app/src/main/assets/vim/pi_spec.html
curl http://vimdoc.sourceforge.net/htmldoc/pi_tar.html > app/src/main/assets/vim/pi_tar.html
curl http://vimdoc.sourceforge.net/htmldoc/pi_vimball.html > app/src/main/assets/vim/pi_vimball.html
curl http://vimdoc.sourceforge.net/htmldoc/pi_zip.html > app/src/main/assets/vim/pi_zip.html
curl http://vimdoc.sourceforge.net/htmldoc/print.html > app/src/main/assets/vim/print.html
curl http://vimdoc.sourceforge.net/htmldoc/quickfix.html > app/src/main/assets/vim/quickfix.html
curl http://vimdoc.sourceforge.net/htmldoc/quickref.html > app/src/main/assets/vim/quickref.html
curl http://vimdoc.sourceforge.net/htmldoc/quotes.html > app/src/main/assets/vim/quotes.html
curl http://vimdoc.sourceforge.net/htmldoc/recover.html > app/src/main/assets/vim/recover.html
curl http://vimdoc.sourceforge.net/htmldoc/remote.html > app/src/main/assets/vim/remote.html
curl http://vimdoc.sourceforge.net/htmldoc/repeat.html > app/src/main/assets/vim/repeat.html
curl http://vimdoc.sourceforge.net/htmldoc/rileft.html > app/src/main/assets/vim/rileft.html
curl http://vimdoc.sourceforge.net/htmldoc/russian.html > app/src/main/assets/vim/russian.html
curl http://vimdoc.sourceforge.net/htmldoc/scroll.html > app/src/main/assets/vim/scroll.html
curl http://vimdoc.sourceforge.net/htmldoc/sign.html > app/src/main/assets/vim/sign.html
curl http://vimdoc.sourceforge.net/htmldoc/spell.html > app/src/main/assets/vim/spell.html
curl http://vimdoc.sourceforge.net/htmldoc/sponsor.html > app/src/main/assets/vim/sponsor.html
curl http://vimdoc.sourceforge.net/htmldoc/starting.html > app/src/main/assets/vim/starting.html
curl http://vimdoc.sourceforge.net/htmldoc/syntax.html > app/src/main/assets/vim/syntax.html
curl http://vimdoc.sourceforge.net/htmldoc/tabpage.html > app/src/main/assets/vim/tabpage.html
curl http://vimdoc.sourceforge.net/htmldoc/tagsrch.html > app/src/main/assets/vim/tagsrch.html
curl http://vimdoc.sourceforge.net/htmldoc/term.html > app/src/main/assets/vim/term.html
curl http://vimdoc.sourceforge.net/htmldoc/tips.html > app/src/main/assets/vim/tips.html
curl http://vimdoc.sourceforge.net/htmldoc/todo.html > app/src/main/assets/vim/todo.html
curl http://vimdoc.sourceforge.net/htmldoc/uganda.html > app/src/main/assets/vim/uganda.html
curl http://vimdoc.sourceforge.net/htmldoc/undo.html > app/src/main/assets/vim/undo.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_01.html > app/src/main/assets/vim/usr_01.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_02.html > app/src/main/assets/vim/usr_02.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_03.html > app/src/main/assets/vim/usr_03.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_04.html > app/src/main/assets/vim/usr_04.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_05.html > app/src/main/assets/vim/usr_05.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_06.html > app/src/main/assets/vim/usr_06.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_07.html > app/src/main/assets/vim/usr_07.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_08.html > app/src/main/assets/vim/usr_08.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_09.html > app/src/main/assets/vim/usr_09.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_10.html > app/src/main/assets/vim/usr_10.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_11.html > app/src/main/assets/vim/usr_11.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_12.html > app/src/main/assets/vim/usr_12.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_20.html > app/src/main/assets/vim/usr_20.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_21.html > app/src/main/assets/vim/usr_21.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_22.html > app/src/main/assets/vim/usr_22.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_23.html > app/src/main/assets/vim/usr_23.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_24.html > app/src/main/assets/vim/usr_24.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_25.html > app/src/main/assets/vim/usr_25.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_26.html > app/src/main/assets/vim/usr_26.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_27.html > app/src/main/assets/vim/usr_27.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_28.html > app/src/main/assets/vim/usr_28.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_29.html > app/src/main/assets/vim/usr_29.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_30.html > app/src/main/assets/vim/usr_30.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_31.html > app/src/main/assets/vim/usr_31.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_32.html > app/src/main/assets/vim/usr_32.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_40.html > app/src/main/assets/vim/usr_40.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_41.html > app/src/main/assets/vim/usr_41.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_42.html > app/src/main/assets/vim/usr_42.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_43.html > app/src/main/assets/vim/usr_43.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_44.html > app/src/main/assets/vim/usr_44.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_45.html > app/src/main/assets/vim/usr_45.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_90.html > app/src/main/assets/vim/usr_90.html
curl http://vimdoc.sourceforge.net/htmldoc/usr_toc.html > app/src/main/assets/vim/usr_toc.html
curl http://vimdoc.sourceforge.net/htmldoc/various.html > app/src/main/assets/vim/various.html
curl http://vimdoc.sourceforge.net/htmldoc/version4.html > app/src/main/assets/vim/version4.html
curl http://vimdoc.sourceforge.net/htmldoc/version5.html > app/src/main/assets/vim/version5.html
curl http://vimdoc.sourceforge.net/htmldoc/version6.html > app/src/main/assets/vim/version6.html
curl http://vimdoc.sourceforge.net/htmldoc/version7.html > app/src/main/assets/vim/version7.html
curl http://vimdoc.sourceforge.net/htmldoc/version8.html > app/src/main/assets/vim/version8.html
curl http://vimdoc.sourceforge.net/htmldoc/vi_diff.html > app/src/main/assets/vim/vi_diff.html
curl http://vimdoc.sourceforge.net/htmldoc/visual.html > app/src/main/assets/vim/visual.html
curl http://vimdoc.sourceforge.net/htmldoc/windows.html > app/src/main/assets/vim/windows.html
curl http://vimdoc.sourceforge.net/htmldoc/workshop.html > app/src/main/assets/vim/workshop.html
