#!/bin/bash

curl http://vimhelp.appspot.com/arabic.txt.html#arabic.txt > app/src/main/assets/vim/arabic.txt.html
curl http://vimhelp.appspot.com/autocmd.txt.html#autocmd.txt > app/src/main/assets/vim/autocmd.txt.html
curl http://vimhelp.appspot.com/change.txt.html#change.txt > app/src/main/assets/vim/change.txt.html
curl http://vimhelp.appspot.com/channel.txt.html#channel.txt > app/src/main/assets/vim/channel.txt.html
curl http://vimhelp.appspot.com/cmdline.txt.html#cmdline.txt > app/src/main/assets/vim/cmdline.txt.html
curl http://vimhelp.appspot.com/debug.txt.html#debug.txt > app/src/main/assets/vim/debug.txt.html
curl http://vimhelp.appspot.com/debugger.txt.html#debugger.txt > app/src/main/assets/vim/debugger.txt.html
curl http://vimhelp.appspot.com/develop.txt.html#develop.txt > app/src/main/assets/vim/develop.txt.html
curl http://vimhelp.appspot.com/diff.txt.html#diff.txt > app/src/main/assets/vim/diff.txt.html
curl http://vimhelp.appspot.com/digraph.txt.html#digraph.txt > app/src/main/assets/vim/digraph.txt.html
curl http://vimhelp.appspot.com/editing.txt.html#editing.txt > app/src/main/assets/vim/editing.txt.html
curl http://vimhelp.appspot.com/eval.txt.html#eval.txt > app/src/main/assets/vim/eval.txt.html
curl http://vimhelp.appspot.com/farsi.txt.html#farsi.txt > app/src/main/assets/vim/farsi.txt.html
curl http://vimhelp.appspot.com/filetype.txt.html#filetype.txt > app/src/main/assets/vim/filetype.txt.html
curl http://vimhelp.appspot.com/fold.txt.html#fold.txt > app/src/main/assets/vim/fold.txt.html
curl http://vimhelp.appspot.com/ft_ada.txt.html#ft_ada.txt > app/src/main/assets/vim/ft_ada.txt.html
curl http://vimhelp.appspot.com/ft_rust.txt.html#ft_rust.txt > app/src/main/assets/vim/ft_rust.txt.html
curl http://vimhelp.appspot.com/ft_sql.txt.html#ft_sql.txt > app/src/main/assets/vim/ft_sql.txt.html
curl http://vimhelp.appspot.com/gui.txt.html#gui.txt > app/src/main/assets/vim/gui.txt.html
curl http://vimhelp.appspot.com/gui_w32.txt.html#gui_w32.txt > app/src/main/assets/vim/gui_w32.txt.html
curl http://vimhelp.appspot.com/gui_x11.txt.html#gui_x11.txt > app/src/main/assets/vim/gui_x11.txt.html
curl http://vimhelp.appspot.com/hangulin.txt.html#hangulin.txt > app/src/main/assets/vim/hangulin.txt.html
curl http://vimhelp.appspot.com/hebrew.txt.html#hebrew.txt > app/src/main/assets/vim/hebrew.txt.html
curl http://vimhelp.appspot.com/#help.txt > app/src/main/assets/vim/help.txt.html
curl http://vimhelp.appspot.com/helphelp.txt.html#helphelp.txt > app/src/main/assets/vim/helphelp.txt.html
curl http://vimhelp.appspot.com/howto.txt.html#howto.txt > app/src/main/assets/vim/howto.txt.html
curl http://vimhelp.appspot.com/if_cscop.txt.html#if_cscop.txt > app/src/main/assets/vim/if_cscop.txt.html
curl http://vimhelp.appspot.com/if_lua.txt.html#if_lua.txt > app/src/main/assets/vim/if_lua.txt.html
curl http://vimhelp.appspot.com/if_mzsch.txt.html#if_mzsch.txt > app/src/main/assets/vim/if_mzsch.txt.html
curl http://vimhelp.appspot.com/if_ole.txt.html#if_ole.txt > app/src/main/assets/vim/if_ole.txt.html
curl http://vimhelp.appspot.com/if_perl.txt.html#if_perl.txt > app/src/main/assets/vim/if_perl.txt.html
curl http://vimhelp.appspot.com/if_pyth.txt.html#if_pyth.txt > app/src/main/assets/vim/if_pyth.txt.html
curl http://vimhelp.appspot.com/if_ruby.txt.html#if_ruby.txt > app/src/main/assets/vim/if_ruby.txt.html
curl http://vimhelp.appspot.com/if_sniff.txt.html#if_sniff.txt > app/src/main/assets/vim/if_sniff.txt.html
curl http://vimhelp.appspot.com/if_tcl.txt.html#if_tcl.txt > app/src/main/assets/vim/if_tcl.txt.html
curl http://vimhelp.appspot.com/indent.txt.html#indent.txt > app/src/main/assets/vim/indent.txt.html
curl http://vimhelp.appspot.com/index.txt.html#index.txt > app/src/main/assets/vim/index.txt.html
curl http://vimhelp.appspot.com/insert.txt.html#insert.txt > app/src/main/assets/vim/insert.txt.html
curl http://vimhelp.appspot.com/intro.txt.html#intro.txt > app/src/main/assets/vim/intro.txt.html
curl http://vimhelp.appspot.com/map.txt.html#map.txt > app/src/main/assets/vim/map.txt.html
curl http://vimhelp.appspot.com/mbyte.txt.html#mbyte.txt > app/src/main/assets/vim/mbyte.txt.html
curl http://vimhelp.appspot.com/message.txt.html#message.txt > app/src/main/assets/vim/message.txt.html
curl http://vimhelp.appspot.com/mlang.txt.html#mlang.txt > app/src/main/assets/vim/mlang.txt.html
curl http://vimhelp.appspot.com/motion.txt.html#motion.txt > app/src/main/assets/vim/motion.txt.html
curl http://vimhelp.appspot.com/netbeans.txt.html#netbeans.txt > app/src/main/assets/vim/netbeans.txt.html
curl http://vimhelp.appspot.com/options.txt.html#options.txt > app/src/main/assets/vim/options.txt.html
curl http://vimhelp.appspot.com/os_390.txt.html#os_390.txt > app/src/main/assets/vim/os_390.txt.html
curl http://vimhelp.appspot.com/os_amiga.txt.html#os_amiga.txt > app/src/main/assets/vim/os_amiga.txt.html
curl http://vimhelp.appspot.com/os_beos.txt.html#os_beos.txt > app/src/main/assets/vim/os_beos.txt.html
curl http://vimhelp.appspot.com/os_dos.txt.html#os_dos.txt > app/src/main/assets/vim/os_dos.txt.html
curl http://vimhelp.appspot.com/os_mac.txt.html#os_mac.txt > app/src/main/assets/vim/os_mac.txt.html
curl http://vimhelp.appspot.com/os_mint.txt.html#os_mint.txt > app/src/main/assets/vim/os_mint.txt.html
curl http://vimhelp.appspot.com/os_msdos.txt.html#os_msdos.txt > app/src/main/assets/vim/os_msdos.txt.html
curl http://vimhelp.appspot.com/os_os2.txt.html#os_os2.txt > app/src/main/assets/vim/os_os2.txt.html
curl http://vimhelp.appspot.com/os_qnx.txt.html#os_qnx.txt > app/src/main/assets/vim/os_qnx.txt.html
curl http://vimhelp.appspot.com/os_risc.txt.html#os_risc.txt > app/src/main/assets/vim/os_risc.txt.html
curl http://vimhelp.appspot.com/os_unix.txt.html#os_unix.txt > app/src/main/assets/vim/os_unix.txt.html
curl http://vimhelp.appspot.com/os_vms.txt.html#os_vms.txt > app/src/main/assets/vim/os_vms.txt.html
curl http://vimhelp.appspot.com/os_win32.txt.html#os_win32.txt > app/src/main/assets/vim/os_win32.txt.html
curl http://vimhelp.appspot.com/pattern.txt.html#pattern.txt > app/src/main/assets/vim/pattern.txt.html
curl http://vimhelp.appspot.com/pi_getscript.txt.html#pi_getscript.txt > app/src/main/assets/vim/pi_getscript.txt.html
curl http://vimhelp.appspot.com/pi_gzip.txt.html#pi_gzip.txt > app/src/main/assets/vim/pi_gzip.txt.html
curl http://vimhelp.appspot.com/pi_logipat.txt.html#pi_logipat.txt > app/src/main/assets/vim/pi_logipat.txt.html
curl http://vimhelp.appspot.com/pi_netrw.txt.html#pi_netrw.txt > app/src/main/assets/vim/pi_netrw.txt.html
curl http://vimhelp.appspot.com/pi_paren.txt.html#pi_paren.txt > app/src/main/assets/vim/pi_paren.txt.html
curl http://vimhelp.appspot.com/pi_spec.txt.html#pi_spec.txt > app/src/main/assets/vim/pi_spec.txt.html
curl http://vimhelp.appspot.com/pi_tar.txt.html#pi_tar.txt > app/src/main/assets/vim/pi_tar.txt.html
curl http://vimhelp.appspot.com/pi_vimball.txt.html#pi_vimball.txt > app/src/main/assets/vim/pi_vimball.txt.html
curl http://vimhelp.appspot.com/pi_zip.txt.html#pi_zip.txt > app/src/main/assets/vim/pi_zip.txt.html
curl http://vimhelp.appspot.com/print.txt.html#print.txt > app/src/main/assets/vim/print.txt.html
curl http://vimhelp.appspot.com/quickfix.txt.html#quickfix.txt > app/src/main/assets/vim/quickfix.txt.html
curl http://vimhelp.appspot.com/quickref.txt.html#quickref.txt > app/src/main/assets/vim/quickref.txt.html
curl http://vimhelp.appspot.com/quotes.txt.html#quotes.txt > app/src/main/assets/vim/quotes.txt.html
curl http://vimhelp.appspot.com/recover.txt.html#recover.txt > app/src/main/assets/vim/recover.txt.html
curl http://vimhelp.appspot.com/remote.txt.html#remote.txt > app/src/main/assets/vim/remote.txt.html
curl http://vimhelp.appspot.com/repeat.txt.html#repeat.txt > app/src/main/assets/vim/repeat.txt.html
curl http://vimhelp.appspot.com/rileft.txt.html#rileft.txt > app/src/main/assets/vim/rileft.txt.html
curl http://vimhelp.appspot.com/russian.txt.html#russian.txt > app/src/main/assets/vim/russian.txt.html
curl http://vimhelp.appspot.com/scroll.txt.html#scroll.txt > app/src/main/assets/vim/scroll.txt.html
curl http://vimhelp.appspot.com/sign.txt.html#sign.txt > app/src/main/assets/vim/sign.txt.html
curl http://vimhelp.appspot.com/spell.txt.html#spell.txt > app/src/main/assets/vim/spell.txt.html
curl http://vimhelp.appspot.com/sponsor.txt.html#sponsor.txt > app/src/main/assets/vim/sponsor.txt.html
curl http://vimhelp.appspot.com/starting.txt.html#starting.txt > app/src/main/assets/vim/starting.txt.html
curl http://vimhelp.appspot.com/syntax.txt.html#syntax.txt > app/src/main/assets/vim/syntax.txt.html
curl http://vimhelp.appspot.com/tabpage.txt.html#tabpage.txt > app/src/main/assets/vim/tabpage.txt.html
curl http://vimhelp.appspot.com/tagsrch.txt.html#tagsrch.txt > app/src/main/assets/vim/tagsrch.txt.html
curl http://vimhelp.appspot.com/term.txt.html#term.txt > app/src/main/assets/vim/term.txt.html
curl http://vimhelp.appspot.com/terminal.txt.html#terminal.txt > app/src/main/assets/vim/terminal.txt.html
curl http://vimhelp.appspot.com/tips.txt.html#tips.txt > app/src/main/assets/vim/tips.txt.html
curl http://vimhelp.appspot.com/todo.txt.html#todo.txt > app/src/main/assets/vim/todo.txt.html
curl http://vimhelp.appspot.com/uganda.txt.html#uganda.txt > app/src/main/assets/vim/uganda.txt.html
curl http://vimhelp.appspot.com/undo.txt.html#undo.txt > app/src/main/assets/vim/undo.txt.html
curl http://vimhelp.appspot.com/usr_01.txt.html#usr_01.txt > app/src/main/assets/vim/usr_01.txt.html
curl http://vimhelp.appspot.com/usr_02.txt.html#usr_02.txt > app/src/main/assets/vim/usr_02.txt.html
curl http://vimhelp.appspot.com/usr_03.txt.html#usr_03.txt > app/src/main/assets/vim/usr_03.txt.html
curl http://vimhelp.appspot.com/usr_04.txt.html#usr_04.txt > app/src/main/assets/vim/usr_04.txt.html
curl http://vimhelp.appspot.com/usr_05.txt.html#usr_05.txt > app/src/main/assets/vim/usr_05.txt.html
curl http://vimhelp.appspot.com/usr_06.txt.html#usr_06.txt > app/src/main/assets/vim/usr_06.txt.html
curl http://vimhelp.appspot.com/usr_07.txt.html#usr_07.txt > app/src/main/assets/vim/usr_07.txt.html
curl http://vimhelp.appspot.com/usr_08.txt.html#usr_08.txt > app/src/main/assets/vim/usr_08.txt.html
curl http://vimhelp.appspot.com/usr_09.txt.html#usr_09.txt > app/src/main/assets/vim/usr_09.txt.html
curl http://vimhelp.appspot.com/usr_10.txt.html#usr_10.txt > app/src/main/assets/vim/usr_10.txt.html
curl http://vimhelp.appspot.com/usr_11.txt.html#usr_11.txt > app/src/main/assets/vim/usr_11.txt.html
curl http://vimhelp.appspot.com/usr_12.txt.html#usr_12.txt > app/src/main/assets/vim/usr_12.txt.html
curl http://vimhelp.appspot.com/usr_20.txt.html#usr_20.txt > app/src/main/assets/vim/usr_20.txt.html
curl http://vimhelp.appspot.com/usr_21.txt.html#usr_21.txt > app/src/main/assets/vim/usr_21.txt.html
curl http://vimhelp.appspot.com/usr_22.txt.html#usr_22.txt > app/src/main/assets/vim/usr_22.txt.html
curl http://vimhelp.appspot.com/usr_23.txt.html#usr_23.txt > app/src/main/assets/vim/usr_23.txt.html
curl http://vimhelp.appspot.com/usr_24.txt.html#usr_24.txt > app/src/main/assets/vim/usr_24.txt.html
curl http://vimhelp.appspot.com/usr_25.txt.html#usr_25.txt > app/src/main/assets/vim/usr_25.txt.html
curl http://vimhelp.appspot.com/usr_26.txt.html#usr_26.txt > app/src/main/assets/vim/usr_26.txt.html
curl http://vimhelp.appspot.com/usr_27.txt.html#usr_27.txt > app/src/main/assets/vim/usr_27.txt.html
curl http://vimhelp.appspot.com/usr_28.txt.html#usr_28.txt > app/src/main/assets/vim/usr_28.txt.html
curl http://vimhelp.appspot.com/usr_29.txt.html#usr_29.txt > app/src/main/assets/vim/usr_29.txt.html
curl http://vimhelp.appspot.com/usr_30.txt.html#usr_30.txt > app/src/main/assets/vim/usr_30.txt.html
curl http://vimhelp.appspot.com/usr_31.txt.html#usr_31.txt > app/src/main/assets/vim/usr_31.txt.html
curl http://vimhelp.appspot.com/usr_32.txt.html#usr_32.txt > app/src/main/assets/vim/usr_32.txt.html
curl http://vimhelp.appspot.com/usr_40.txt.html#usr_40.txt > app/src/main/assets/vim/usr_40.txt.html
curl http://vimhelp.appspot.com/usr_41.txt.html#usr_41.txt > app/src/main/assets/vim/usr_41.txt.html
curl http://vimhelp.appspot.com/usr_42.txt.html#usr_42.txt > app/src/main/assets/vim/usr_42.txt.html
curl http://vimhelp.appspot.com/usr_43.txt.html#usr_43.txt > app/src/main/assets/vim/usr_43.txt.html
curl http://vimhelp.appspot.com/usr_44.txt.html#usr_44.txt > app/src/main/assets/vim/usr_44.txt.html
curl http://vimhelp.appspot.com/usr_45.txt.html#usr_45.txt > app/src/main/assets/vim/usr_45.txt.html
curl http://vimhelp.appspot.com/usr_90.txt.html#usr_90.txt > app/src/main/assets/vim/usr_90.txt.html
curl http://vimhelp.appspot.com/usr_toc.txt.html#usr_toc.txt > app/src/main/assets/vim/usr_toc.txt.html
curl http://vimhelp.appspot.com/various.txt.html#various.txt > app/src/main/assets/vim/various.txt.html
curl http://vimhelp.appspot.com/version4.txt.html#version4.txt > app/src/main/assets/vim/version4.txt.html
curl http://vimhelp.appspot.com/version5.txt.html#version5.txt > app/src/main/assets/vim/version5.txt.html
curl http://vimhelp.appspot.com/version6.txt.html#version6.txt > app/src/main/assets/vim/version6.txt.html
curl http://vimhelp.appspot.com/version7.txt.html#version7.txt > app/src/main/assets/vim/version7.txt.html
curl http://vimhelp.appspot.com/version8.txt.html#version8.txt > app/src/main/assets/vim/version8.txt.html
curl http://vimhelp.appspot.com/vi_diff.txt.html#vi_diff.txt > app/src/main/assets/vim/vi_diff.txt.html
curl http://vimhelp.appspot.com/visual.txt.html#visual.txt > app/src/main/assets/vim/visual.txt.html
curl http://vimhelp.appspot.com/windows.txt.html#windows.txt > app/src/main/assets/vim/windows.txt.html
curl http://vimhelp.appspot.com/workshop.txt.html#workshop.txt > app/src/main/assets/vim/workshop.txt.html
