#! /bin/bash

mkdir app/src/main/assets/tmpneovim

# curl https://neovim.io/images/logo@2x.png > app/src/main/assets/neovim/logo@2x.png
curl https://neovim.io/doc/user/api.html > app/src/main/assets/tmpneovim/api.html
curl https://neovim.io/doc/user/arabic.html > app/src/main/assets/tmpneovim/arabic.html
curl https://neovim.io/doc/user/autocmd.html > app/src/main/assets/tmpneovim/autocmd.html
curl https://neovim.io/doc/user/change.html > app/src/main/assets/tmpneovim/change.html
curl https://neovim.io/doc/user/channel.html > app/src/main/assets/tmpneovim/channel.html
curl https://neovim.io/doc/user/cmdline.html > app/src/main/assets/tmpneovim/cmdline.html
curl https://neovim.io/doc/user/debug.html > app/src/main/assets/tmpneovim/debug.html
curl https://neovim.io/doc/user/deprecated.html > app/src/main/assets/tmpneovim/deprecated.html
curl https://neovim.io/doc/user/develop.html > app/src/main/assets/tmpneovim/develop.html
curl https://neovim.io/doc/user/diff.html > app/src/main/assets/tmpneovim/diff.html
curl https://neovim.io/doc/user/digraph.html > app/src/main/assets/tmpneovim/digraph.html
curl https://neovim.io/doc/user/editing.html > app/src/main/assets/tmpneovim/editing.html
curl https://neovim.io/doc/user/eval.html > app/src/main/assets/tmpneovim/eval.html
curl https://neovim.io/doc/user/farsi.html > app/src/main/assets/tmpneovim/farsi.html
curl https://neovim.io/doc/user/filetype.html > app/src/main/assets/tmpneovim/filetype.html
curl https://neovim.io/doc/user/fold.html > app/src/main/assets/tmpneovim/fold.html
curl https://neovim.io/doc/user/ft_ada.html > app/src/main/assets/tmpneovim/ft_ada.html
curl https://neovim.io/doc/user/ft_rust.html > app/src/main/assets/tmpneovim/ft_rust.html
curl https://neovim.io/doc/user/ft_sql.html > app/src/main/assets/tmpneovim/ft_sql.html
curl https://neovim.io/doc/user/gui.html > app/src/main/assets/tmpneovim/gui.html
curl https://neovim.io/doc/user/hebrew.html > app/src/main/assets/tmpneovim/hebrew.html
curl https://neovim.io/doc/user/help.html > app/src/main/assets/tmpneovim/help.html
curl https://neovim.io/doc/user/helphelp.html > app/src/main/assets/tmpneovim/helphelp.html
curl https://neovim.io/doc/user/if_cscop.html > app/src/main/assets/tmpneovim/if_cscop.html
curl https://neovim.io/doc/user/if_lua.html > app/src/main/assets/tmpneovim/if_lua.html
curl https://neovim.io/doc/user/if_pyth.html > app/src/main/assets/tmpneovim/if_pyth.html
curl https://neovim.io/doc/user/if_ruby.html > app/src/main/assets/tmpneovim/if_ruby.html
curl https://neovim.io/doc/user/indent.html > app/src/main/assets/tmpneovim/indent.html
curl https://neovim.io/doc/user/index.html > app/src/main/assets/tmpneovim/index.html
curl https://neovim.io/doc/user/insert.html > app/src/main/assets/tmpneovim/insert.html
curl https://neovim.io/doc/user/intro.html > app/src/main/assets/tmpneovim/intro.html
curl https://neovim.io/doc/user/job_control.html > app/src/main/assets/tmpneovim/job_control.html
curl https://neovim.io/doc/user/map.html > app/src/main/assets/tmpneovim/map.html
curl https://neovim.io/doc/user/mbyte.html > app/src/main/assets/tmpneovim/mbyte.html
curl https://neovim.io/doc/user/message.html > app/src/main/assets/tmpneovim/message.html
curl https://neovim.io/doc/user/mlang.html > app/src/main/assets/tmpneovim/mlang.html
curl https://neovim.io/doc/user/motion.html > app/src/main/assets/tmpneovim/motion.html
curl https://neovim.io/doc/user/msgpack_rpc.html > app/src/main/assets/tmpneovim/msgpack_rpc.html
curl https://neovim.io/doc/user/nvim.html > app/src/main/assets/tmpneovim/nvim.html
curl https://neovim.io/doc/user/nvim_terminal_emulator.html > app/src/main/assets/tmpneovim/nvim_terminal_emulator.html
curl https://neovim.io/doc/user/options.html > app/src/main/assets/tmpneovim/options.html
curl https://neovim.io/doc/user/pattern.html > app/src/main/assets/tmpneovim/pattern.html
curl https://neovim.io/doc/user/pi_gzip.html > app/src/main/assets/tmpneovim/pi_gzip.html
curl https://neovim.io/doc/user/pi_health.html > app/src/main/assets/tmpneovim/pi_health.html
curl https://neovim.io/doc/user/pi_matchit.html > app/src/main/assets/tmpneovim/pi_matchit.html
curl https://neovim.io/doc/user/pi_msgpack.html > app/src/main/assets/tmpneovim/pi_msgpack.html
curl https://neovim.io/doc/user/pi_netrw.html > app/src/main/assets/tmpneovim/pi_netrw.html
curl https://neovim.io/doc/user/pi_paren.html > app/src/main/assets/tmpneovim/pi_paren.html
curl https://neovim.io/doc/user/pi_spec.html > app/src/main/assets/tmpneovim/pi_spec.html
curl https://neovim.io/doc/user/pi_tar.html > app/src/main/assets/tmpneovim/pi_tar.html
curl https://neovim.io/doc/user/pi_tutor.html > app/src/main/assets/tmpneovim/pi_tutor.html
curl https://neovim.io/doc/user/pi_zip.html > app/src/main/assets/tmpneovim/pi_zip.html
curl https://neovim.io/doc/user/print.html > app/src/main/assets/tmpneovim/print.html
curl https://neovim.io/doc/user/provider.html > app/src/main/assets/tmpneovim/provider.html
curl https://neovim.io/doc/user/quickfix.html > app/src/main/assets/tmpneovim/quickfix.html
curl https://neovim.io/doc/user/quickref.html > app/src/main/assets/tmpneovim/quickref.html
curl https://neovim.io/doc/user/recover.html > app/src/main/assets/tmpneovim/recover.html
curl https://neovim.io/doc/user/remote.html > app/src/main/assets/tmpneovim/remote.html
curl https://neovim.io/doc/user/remote_plugin.html > app/src/main/assets/tmpneovim/remote_plugin.html
curl https://neovim.io/doc/user/repeat.html > app/src/main/assets/tmpneovim/repeat.html
curl https://neovim.io/doc/user/rileft.html > app/src/main/assets/tmpneovim/rileft.html
curl https://neovim.io/doc/user/russian.html > app/src/main/assets/tmpneovim/russian.html
curl https://neovim.io/doc/user/scroll.html > app/src/main/assets/tmpneovim/scroll.html
curl https://neovim.io/doc/user/sign.html > app/src/main/assets/tmpneovim/sign.html
curl https://neovim.io/doc/user/spell.html > app/src/main/assets/tmpneovim/spell.html
curl https://neovim.io/doc/user/sponsor.html > app/src/main/assets/tmpneovim/sponsor.html
curl https://neovim.io/doc/user/starting.html > app/src/main/assets/tmpneovim/starting.html
curl https://neovim.io/doc/user/syntax.html > app/src/main/assets/tmpneovim/syntax.html
curl https://neovim.io/doc/user/tabpage.html > app/src/main/assets/tmpneovim/tabpage.html
curl https://neovim.io/doc/user/tagsrch.html > app/src/main/assets/tmpneovim/tagsrch.html
curl https://neovim.io/doc/user/term.html > app/src/main/assets/tmpneovim/term.html
curl https://neovim.io/doc/user/tips.html > app/src/main/assets/tmpneovim/tips.html
curl https://neovim.io/doc/user/uganda.html > app/src/main/assets/tmpneovim/uganda.html
curl https://neovim.io/doc/user/ui.html > app/src/main/assets/tmpneovim/ui.html
curl https://neovim.io/doc/user/undo.html > app/src/main/assets/tmpneovim/undo.html
curl https://neovim.io/doc/user/usr_01.html > app/src/main/assets/tmpneovim/usr_01.html
curl https://neovim.io/doc/user/usr_02.html > app/src/main/assets/tmpneovim/usr_02.html
curl https://neovim.io/doc/user/usr_03.html > app/src/main/assets/tmpneovim/usr_03.html
curl https://neovim.io/doc/user/usr_04.html > app/src/main/assets/tmpneovim/usr_04.html
curl https://neovim.io/doc/user/usr_05.html > app/src/main/assets/tmpneovim/usr_05.html
curl https://neovim.io/doc/user/usr_06.html > app/src/main/assets/tmpneovim/usr_06.html
curl https://neovim.io/doc/user/usr_07.html > app/src/main/assets/tmpneovim/usr_07.html
curl https://neovim.io/doc/user/usr_08.html > app/src/main/assets/tmpneovim/usr_08.html
curl https://neovim.io/doc/user/usr_09.html > app/src/main/assets/tmpneovim/usr_09.html
curl https://neovim.io/doc/user/usr_10.html > app/src/main/assets/tmpneovim/usr_10.html
curl https://neovim.io/doc/user/usr_11.html > app/src/main/assets/tmpneovim/usr_11.html
curl https://neovim.io/doc/user/usr_12.html > app/src/main/assets/tmpneovim/usr_12.html
curl https://neovim.io/doc/user/usr_20.html > app/src/main/assets/tmpneovim/usr_20.html
curl https://neovim.io/doc/user/usr_21.html > app/src/main/assets/tmpneovim/usr_21.html
curl https://neovim.io/doc/user/usr_22.html > app/src/main/assets/tmpneovim/usr_22.html
curl https://neovim.io/doc/user/usr_23.html > app/src/main/assets/tmpneovim/usr_23.html
curl https://neovim.io/doc/user/usr_24.html > app/src/main/assets/tmpneovim/usr_24.html
curl https://neovim.io/doc/user/usr_25.html > app/src/main/assets/tmpneovim/usr_25.html
curl https://neovim.io/doc/user/usr_26.html > app/src/main/assets/tmpneovim/usr_26.html
curl https://neovim.io/doc/user/usr_27.html > app/src/main/assets/tmpneovim/usr_27.html
curl https://neovim.io/doc/user/usr_28.html > app/src/main/assets/tmpneovim/usr_28.html
curl https://neovim.io/doc/user/usr_29.html > app/src/main/assets/tmpneovim/usr_29.html
curl https://neovim.io/doc/user/usr_30.html > app/src/main/assets/tmpneovim/usr_30.html
curl https://neovim.io/doc/user/usr_31.html > app/src/main/assets/tmpneovim/usr_31.html
curl https://neovim.io/doc/user/usr_32.html > app/src/main/assets/tmpneovim/usr_32.html
curl https://neovim.io/doc/user/usr_40.html > app/src/main/assets/tmpneovim/usr_40.html
curl https://neovim.io/doc/user/usr_41.html > app/src/main/assets/tmpneovim/usr_41.html
curl https://neovim.io/doc/user/usr_42.html > app/src/main/assets/tmpneovim/usr_42.html
curl https://neovim.io/doc/user/usr_43.html > app/src/main/assets/tmpneovim/usr_43.html
curl https://neovim.io/doc/user/usr_44.html > app/src/main/assets/tmpneovim/usr_44.html
curl https://neovim.io/doc/user/usr_45.html > app/src/main/assets/tmpneovim/usr_45.html
curl https://neovim.io/doc/user/usr_toc.html > app/src/main/assets/tmpneovim/usr_toc.html
curl https://neovim.io/doc/user/various.html > app/src/main/assets/tmpneovim/various.html
curl https://neovim.io/doc/user/vi_diff.html > app/src/main/assets/tmpneovim/vi_diff.html
curl https://neovim.io/doc/user/vim_diff.html > app/src/main/assets/tmpneovim/vim_diff.html
curl https://neovim.io/doc/user/visual.html > app/src/main/assets/tmpneovim/visual.html
curl https://neovim.io/doc/user/windows.html > app/src/main/assets/tmpneovim/windows.html
