#!/bin/bash

curl https://neovim.io/images/logo@2x.png > app/src/main/assets/neovim/logo@2x.png
curl https://neovim.io/doc/user/api.html > app/src/main/assets/neovim/api.html
curl https://neovim.io/doc/user/arabic.html > app/src/main/assets/neovim/arabic.html
curl https://neovim.io/doc/user/autocmd.html > app/src/main/assets/neovim/autocmd.html
curl https://neovim.io/doc/user/change.html > app/src/main/assets/neovim/change.html
curl https://neovim.io/doc/user/cmdline.html > app/src/main/assets/neovim/cmdline.html
curl https://neovim.io/doc/user/debug.html > app/src/main/assets/neovim/debug.html
curl https://neovim.io/doc/user/deprecated.html > app/src/main/assets/neovim/deprecated.html
curl https://neovim.io/doc/user/develop.html > app/src/main/assets/neovim/develop.html
curl https://neovim.io/doc/user/diff.html > app/src/main/assets/neovim/diff.html
curl https://neovim.io/doc/user/digraph.html > app/src/main/assets/neovim/digraph.html
curl https://neovim.io/doc/user/editing.html > app/src/main/assets/neovim/editing.html
curl https://neovim.io/doc/user/eval.html > app/src/main/assets/neovim/eval.html
curl https://neovim.io/doc/user/farsi.html > app/src/main/assets/neovim/farsi.html
curl https://neovim.io/doc/user/filetype.html > app/src/main/assets/neovim/filetype.html
curl https://neovim.io/doc/user/fold.html > app/src/main/assets/neovim/fold.html
curl https://neovim.io/doc/user/ft_ada.html > app/src/main/assets/neovim/ft_ada.html
curl https://neovim.io/doc/user/ft_rust.html > app/src/main/assets/neovim/ft_rust.html
curl https://neovim.io/doc/user/ft_sql.html > app/src/main/assets/neovim/ft_sql.html
curl https://neovim.io/doc/user/gui.html > app/src/main/assets/neovim/gui.html
curl https://neovim.io/doc/user/hebrew.html > app/src/main/assets/neovim/hebrew.html
curl https://neovim.io/doc/user/help.html > app/src/main/assets/neovim/help.html
curl https://neovim.io/doc/user/helphelp.html > app/src/main/assets/neovim/helphelp.html
curl https://neovim.io/doc/user/if_cscop.html > app/src/main/assets/neovim/if_cscop.html
curl https://neovim.io/doc/user/if_lua.html > app/src/main/assets/neovim/if_lua.html
curl https://neovim.io/doc/user/if_pyth.html > app/src/main/assets/neovim/if_pyth.html
curl https://neovim.io/doc/user/if_ruby.html > app/src/main/assets/neovim/if_ruby.html
curl https://neovim.io/doc/user/indent.html > app/src/main/assets/neovim/indent.html
curl https://neovim.io/doc/user/index.html > app/src/main/assets/neovim/index.html
curl https://neovim.io/doc/user/insert.html > app/src/main/assets/neovim/insert.html
curl https://neovim.io/doc/user/intro.html > app/src/main/assets/neovim/intro.html
curl https://neovim.io/doc/user/job_control.html > app/src/main/assets/neovim/job_control.html
curl https://neovim.io/doc/user/map.html > app/src/main/assets/neovim/map.html
curl https://neovim.io/doc/user/mbyte.html > app/src/main/assets/neovim/mbyte.html
curl https://neovim.io/doc/user/message.html > app/src/main/assets/neovim/message.html
curl https://neovim.io/doc/user/mlang.html > app/src/main/assets/neovim/mlang.html
curl https://neovim.io/doc/user/motion.html > app/src/main/assets/neovim/motion.html
curl https://neovim.io/doc/user/msgpack_rpc.html > app/src/main/assets/neovim/msgpack_rpc.html
curl https://neovim.io/doc/user/nvim.html > app/src/main/assets/neovim/nvim.html
curl https://neovim.io/doc/user/nvim_terminal_emulator.html > app/src/main/assets/neovim/nvim_terminal_emulator.html
curl https://neovim.io/doc/user/options.html > app/src/main/assets/neovim/options.html
curl https://neovim.io/doc/user/pattern.html > app/src/main/assets/neovim/pattern.html
curl https://neovim.io/doc/user/pi_gzip.html > app/src/main/assets/neovim/pi_gzip.html
curl https://neovim.io/doc/user/pi_health.html > app/src/main/assets/neovim/pi_health.html
curl https://neovim.io/doc/user/pi_matchit.html > app/src/main/assets/neovim/pi_matchit.html
curl https://neovim.io/doc/user/pi_msgpack.html > app/src/main/assets/neovim/pi_msgpack.html
curl https://neovim.io/doc/user/pi_netrw.html > app/src/main/assets/neovim/pi_netrw.html
curl https://neovim.io/doc/user/pi_paren.html > app/src/main/assets/neovim/pi_paren.html
curl https://neovim.io/doc/user/pi_spec.html > app/src/main/assets/neovim/pi_spec.html
curl https://neovim.io/doc/user/pi_tar.html > app/src/main/assets/neovim/pi_tar.html
curl https://neovim.io/doc/user/pi_tutor.html > app/src/main/assets/neovim/pi_tutor.html
curl https://neovim.io/doc/user/pi_zip.html > app/src/main/assets/neovim/pi_zip.html
curl https://neovim.io/doc/user/print.html > app/src/main/assets/neovim/print.html
curl https://neovim.io/doc/user/provider.html > app/src/main/assets/neovim/provider.html
curl https://neovim.io/doc/user/quickfix.html > app/src/main/assets/neovim/quickfix.html
curl https://neovim.io/doc/user/quickref.html > app/src/main/assets/neovim/quickref.html
curl https://neovim.io/doc/user/recover.html > app/src/main/assets/neovim/recover.html
curl https://neovim.io/doc/user/remote.html > app/src/main/assets/neovim/remote.html
curl https://neovim.io/doc/user/remote_plugin.html > app/src/main/assets/neovim/remote_plugin.html
curl https://neovim.io/doc/user/repeat.html > app/src/main/assets/neovim/repeat.html
curl https://neovim.io/doc/user/rileft.html > app/src/main/assets/neovim/rileft.html
curl https://neovim.io/doc/user/russian.html > app/src/main/assets/neovim/russian.html
curl https://neovim.io/doc/user/scroll.html > app/src/main/assets/neovim/scroll.html
curl https://neovim.io/doc/user/sign.html > app/src/main/assets/neovim/sign.html
curl https://neovim.io/doc/user/spell.html > app/src/main/assets/neovim/spell.html
curl https://neovim.io/doc/user/sponsor.html > app/src/main/assets/neovim/sponsor.html
curl https://neovim.io/doc/user/starting.html > app/src/main/assets/neovim/starting.html
curl https://neovim.io/doc/user/syntax.html > app/src/main/assets/neovim/syntax.html
curl https://neovim.io/doc/user/tabpage.html > app/src/main/assets/neovim/tabpage.html
curl https://neovim.io/doc/user/tagsrch.html > app/src/main/assets/neovim/tagsrch.html
curl https://neovim.io/doc/user/term.html > app/src/main/assets/neovim/term.html
curl https://neovim.io/doc/user/tips.html > app/src/main/assets/neovim/tips.html
curl https://neovim.io/doc/user/uganda.html > app/src/main/assets/neovim/uganda.html
curl https://neovim.io/doc/user/ui.html > app/src/main/assets/neovim/ui.html
curl https://neovim.io/doc/user/undo.html > app/src/main/assets/neovim/undo.html
curl https://neovim.io/doc/user/usr_01.html > app/src/main/assets/neovim/usr_01.html
curl https://neovim.io/doc/user/usr_02.html > app/src/main/assets/neovim/usr_02.html
curl https://neovim.io/doc/user/usr_03.html > app/src/main/assets/neovim/usr_03.html
curl https://neovim.io/doc/user/usr_04.html > app/src/main/assets/neovim/usr_04.html
curl https://neovim.io/doc/user/usr_05.html > app/src/main/assets/neovim/usr_05.html
curl https://neovim.io/doc/user/usr_06.html > app/src/main/assets/neovim/usr_06.html
curl https://neovim.io/doc/user/usr_07.html > app/src/main/assets/neovim/usr_07.html
curl https://neovim.io/doc/user/usr_08.html > app/src/main/assets/neovim/usr_08.html
curl https://neovim.io/doc/user/usr_09.html > app/src/main/assets/neovim/usr_09.html
curl https://neovim.io/doc/user/usr_10.html > app/src/main/assets/neovim/usr_10.html
curl https://neovim.io/doc/user/usr_11.html > app/src/main/assets/neovim/usr_11.html
curl https://neovim.io/doc/user/usr_12.html > app/src/main/assets/neovim/usr_12.html
curl https://neovim.io/doc/user/usr_20.html > app/src/main/assets/neovim/usr_20.html
curl https://neovim.io/doc/user/usr_21.html > app/src/main/assets/neovim/usr_21.html
curl https://neovim.io/doc/user/usr_22.html > app/src/main/assets/neovim/usr_22.html
curl https://neovim.io/doc/user/usr_23.html > app/src/main/assets/neovim/usr_23.html
curl https://neovim.io/doc/user/usr_24.html > app/src/main/assets/neovim/usr_24.html
curl https://neovim.io/doc/user/usr_25.html > app/src/main/assets/neovim/usr_25.html
curl https://neovim.io/doc/user/usr_26.html > app/src/main/assets/neovim/usr_26.html
curl https://neovim.io/doc/user/usr_27.html > app/src/main/assets/neovim/usr_27.html
curl https://neovim.io/doc/user/usr_28.html > app/src/main/assets/neovim/usr_28.html
curl https://neovim.io/doc/user/usr_29.html > app/src/main/assets/neovim/usr_29.html
curl https://neovim.io/doc/user/usr_30.html > app/src/main/assets/neovim/usr_30.html
curl https://neovim.io/doc/user/usr_31.html > app/src/main/assets/neovim/usr_31.html
curl https://neovim.io/doc/user/usr_32.html > app/src/main/assets/neovim/usr_32.html
curl https://neovim.io/doc/user/usr_40.html > app/src/main/assets/neovim/usr_40.html
curl https://neovim.io/doc/user/usr_41.html > app/src/main/assets/neovim/usr_41.html
curl https://neovim.io/doc/user/usr_42.html > app/src/main/assets/neovim/usr_42.html
curl https://neovim.io/doc/user/usr_43.html > app/src/main/assets/neovim/usr_43.html
curl https://neovim.io/doc/user/usr_44.html > app/src/main/assets/neovim/usr_44.html
curl https://neovim.io/doc/user/usr_45.html > app/src/main/assets/neovim/usr_45.html
curl https://neovim.io/doc/user/usr_toc.html > app/src/main/assets/neovim/usr_toc.html
curl https://neovim.io/doc/user/various.html > app/src/main/assets/neovim/various.html
curl https://neovim.io/doc/user/vi_diff.html > app/src/main/assets/neovim/vi_diff.html
curl https://neovim.io/doc/user/vim_diff.html > app/src/main/assets/neovim/vim_diff.html
curl https://neovim.io/doc/user/visual.html > app/src/main/assets/neovim/visual.html
curl https://neovim.io/doc/user/windows.html > app/src/main/assets/neovim/windows.html
